### ISSUE TITLE
No xml found under https://jakarta.ee/xml/ns/jaxb

### ISSUE THREAD

**Issue by sumitAgrawal007** [eclipse-ee4j/jaxb-ri#1500] opened 2021-01-05 11:07 UTC
The episode file generated using jaxb-ri 3.0 release with -episode flag, has the line

bindings version="3.0" xmlns="https://jakarta.ee/xml/ns/jaxb"

But "https://jakarta.ee/xml/ns/jaxb" is throwing error, "**NO XML found at this location**"
This is causing error.

**Comment by lukasj** [comment] 2021-01-05 11:13
can you provide some (minimal) test case for this, please?

**Comment by sumitAgrawal007** [comment] 2021-01-05 16:53
When you say testcase, what exactly are needed ?
The command used was
./jaxb-ri/bin/xjc.sh -episode vim.episode $WSDLDIR/vim-types.xsd -d . -p com.vmware.vim25 

The contents of the generated .episode file.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<bindings version="3.0" xmlns="https://jakarta.ee/xml/ns/jaxb">
  <!--

This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
See https://eclipse-ee4j.github.io/jaxb-ri 
Any modifications to this file will be lost upon recompilation of the source schema. 
Generated on: 2021.01.05 at 07:22:23 PM IST 

  -->
  <bindings scd="x-schema::tns" xmlns:tns="urn:vim25">
    <schemaBindings map="false">
      <package name="com.vmware.vim25"/>
    </schemaBindings>
    <bindings scd="~tns:DynamicArray">
      <class ref="com.vmware.vim25.DynamicArray"/>
    </bindings>
    <bindings scd="~tns:DynamicData">
      <class ref="com.vmware.vim25.DynamicData"/>
    </bindings>
    <bindings scd="~tns:DynamicProperty">
      <class ref="com.vmware.vim25.DynamicProperty"/>
    </bindings>
    <bindings scd="~tns:ArrayOfDynamicProperty">
      <class ref="com.vmware.vim25.ArrayOfDynamicProperty"/>
    </bindings>
    <bindings scd="~tns:KeyAnyValue">
      <class ref="com.vmware.vim25.KeyAnyValue"/>
    </bindings>
</bindings>

```

**Comment by lukasj** [comment] 2021-01-05 17:17
> When you say testcase, what exactly are needed ?

something one can just unzip and run or some steps to reproduce the behaviour you are seeing. Running `./xjc.sh -episode vim.episode https://raw.githubusercontent.com/vadimcomanescu/vmwarephp/master/library/Vmwarephp/Wsdl/vim-types.xsd -d . -p com.vmware.vim25` is just a first step - it creates the episode file and does not cause any error as such. Having the next command where the episode file is being consumed would be helpful as well to properly verify the fix on your input.

**Comment by sumitAgrawal007** [comment] 2021-01-06 14:33
Please unzip the given file,
[zipped Repo](https://onevmw-my.sharepoint.com/:u:/g/personal/asumit_vmware_com/EbHdsheDi9lMv7Iu7tCqWgcB2s9cfXJntQ1ECPb-3IHZag?e=bjy2Oj)

cd SDK-test/spbm/java/JAXWS
Run sh build.sh
It generates the .episode file, but on the next step while generating the stubs, the episode file is not picked up.

sh $JAXWS_HOME/bin/wsimport.sh -wsdllocation $WSDLNAME -b vim.episode  -p com.vmware.$PRODUCT -s . ${WSDLDIR}/${WSDLNAME} -Xnocompile -quiet

And subsequently, the Samples compiling fails.
javac -classpath "$JAXWS_HOME/lib/*:$LIB_DIR/*" -source 1.8 -target 1.8 ${SAMPLE_SRC_FILES}

But if you replace the  **bindings version="3.0" xmlns="https://jakarta.ee/xml/ns/jaxb"**  with **bindings version="2.1" xmlns="http://java.sun.com/xml/ns/jaxb** , the episode file gets picked up correctly and samples get compiled.

You can uncomment this line **#sed -i -e 's%<bindings version="3.0" xmlns="https://jakarta.ee/xml/ns/jaxb">%<bindings version="2.1" xmlns="http://java.sun.com/xml/ns/jaxb">%g' vim.episode**
in the script, and see that it compiles.


I suspect, the https://jakarta.ee/xml/ns/jaxb URL is not correct, intellij idea complains that there is not XML found there.

**Comment by lukasj** [comment] 2021-01-06 14:49
the NS as such is correct, the schema itself is at https://jakarta.ee/xml/ns/jaxb/bindingschema_3_0.xsd; the bug is likely in the version not being bumped to '3.0' somewhere in xjc code.

Thanks for the test case, it's going to make fixing this easier/faster.

**Comment by lukasj** [comment] 2021-01-18 23:24
the problem here is that JAXB-RI 3.0.0 is being used with JAXWS-RI 2.3.3. These two versions are not compatible. After updating JAXWS-RI in given sample app to 3.0.0, compilation succeeds and everything seems to be fine. Therefor closing as not a bug.

**Closed by lukasj** 2021-01-18 23:24 UTC
