### ISSUE TITLE
Java 9: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1197] opened 2018-05-06 03:27 UTC
With Java 9 or 10, using
```
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>2.3.0</version>
            </dependency>
```
results in:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector 
(file: repository/org/glassfish/jaxb/jaxb-runtime/2.3.0/jaxb-runtime-2.3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by bravehorsie** [comment] 2018-10-11 11:04
Fixed in 2.3.1

**Closed by bravehorsie** 2018-10-11 11:04 UTC

**Comment by sify21** [comment] 2021-01-21 09:38
Hi I'm using `org.glassfish.jaxb:jaxb-runtime:3.0.0`, and this warning comes back

**Comment by bourgesl** [comment] 2021-03-31 09:10
Hi,

I tested my jaxb application (compiled with JDK8) with JDK 16 (openjdk) and it fails with the exception:
```
ERROR [main] com.sun.xml.bind.v2.runtime.reflect.opt.Injector - null
    java.security.PrivilegedActionException: null
    Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
    at java.base/java.lang.Class.getMethod(Class.java:2195)
    at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:170)
    at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:166)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
```

I upgrade to the lastest JAXB 2.3 release (no 2.4 release yet) as I need wide java version compatibility (8 to 17). 
I can not switch to JAXB RI 3.0 (JDK11+, no jdk8 support) as it implies a migration effort to jakarta.xml packages and re-generate all JAXB code to comply with this package renaming).

To fix the problem with JDK16, I must explicitely set one of the following system properties before calling JAXBContext.newInstance(...):
```
    System.setProperty("com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.noOptimization", "true");
or
    System.setProperty("com.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize", "true");
```
Which property is better to use ? 
I figured out myself that 'OptimizedAccessorFactory.noOptimization' is good, but you promote using 'ClassTailor.noOptimize'. Could you explain the difference ?

Would it be possible to detect JDK16 in jaxb 2.3.x or 2.4 (JDK8 compatible) and disable such (unsupported) optimization ?


Here are my concrete maven (explicit) dependencies to use JAXB 2.3.3 in my project:
```
        <!-- JAXB 2.3.3 (jdk 8+) -->
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.3</version>
        </dependency>

        <!-- JAXB dependencies -->
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>jakarta.activation</artifactId>
            <version>1.2.2</version>
        </dependency>

        <dependency>
            <groupId>com.sun.istack</groupId>
            <artifactId>istack-commons-runtime</artifactId>
            <version>3.0.11</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.fastinfoset</groupId>
            <artifactId>FastInfoset</artifactId>
            <version>1.2.18</version>
        </dependency>
        <dependency>
            <groupId>org.jvnet.staxex</groupId>
            <artifactId>stax-ex</artifactId>
            <version>1.8.3</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>txw2</artifactId>
            <version>2.3.3</version>
        </dependency>
```

**Comment by lukasj** [comment] 2021-03-31 09:28
Does passing `-Djdk.util.jar.enableMultiRelease=force` to JVM make any difference?

**Comment by bourgesl** [comment] 2021-03-31 09:40
In my case, the application is build on JDK8 (to be sure it works on java 8) as a single fat jar or exploded classpath. As I am not using modules yet, I have no idea.

Moreover, it is a desktop application so I can not ask users to define magic flags on the command line, but I can set few needed system properties in my code:
```
    /** JAXB implementation 2.3.x provided in project libraries */
    private static final String JAXB_CONTEXT_FACTORY_IMPLEMENTATION = "com.sun.xml.bind.v2.ContextFactory";

    static {
        // Define the system property to define which JAXB implementation to use:
        System.setProperty("javax.xml.bind.JAXBContextFactory", JAXB_CONTEXT_FACTORY_IMPLEMENTATION);
        System.setProperty(JAXBContext.JAXB_CONTEXT_FACTORY, JAXB_CONTEXT_FACTORY_IMPLEMENTATION);

        if (org.apache.commons.lang.SystemUtils.JAVA_VERSION_FLOAT >= 16.0f) {
            // JDK16 support fix:
            /*
                ERROR [main] com.sun.xml.bind.v2.runtime.reflect.opt.Injector - null
                java.security.PrivilegedActionException: null
                Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
                    at java.base/java.lang.Class.getMethod(Class.java:2195)
                    at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:170)
                    at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:166)
                    at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
            */
            final String key = "com.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize";
            System.setProperty(key, "true");
            logger.info("Fix JDK-16+ support: version = {} (set {} = true)", 
                    org.apache.commons.lang.SystemUtils.JAVA_VERSION_FLOAT, key);
        }
        logger.info("JAXB ContextFactory: {}", System.getProperty(JAXBContext.JAXB_CONTEXT_FACTORY));
    }
```

**Comment by lukasj** [comment] 2021-03-31 09:46
> In my case, the application is build on JDK8 (to be sure it works on java 8) as a single fat jar or exploded classpath. As I am not using modules yet, I have no idea.

So this the cause of your troubles and reason I won't be able to reproduce the issue on my end. Your app needs to have `META-INF/versions` folder and be marked as `Multi-Release: true` in manifest if you want it to work properly on JDKs 8-17 at the same time. Take a look what multirelease jar files are about: https://openjdk.java.net/jeps/238

**Comment by bourgesl** [comment] 2021-03-31 10:06
Thanks.
My fat jar already had META-INF/versions folder but 'Multi-Release: true' was missing in the MANIFEST.MF !
I will get rid of my JDK16 fix as it works now like a charm !
