### ISSUE TITLE
"Zero length BigInteger" error when unmarshaling

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1193] opened 2018-04-27 22:32 UTC
Previously tracked via: https://bugs.openjdk.java.net/browse/JDK-8074027

Let's consider following XSD and XML document: 

    <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"> 

    <xsd:element name="root"> 
       <xsd:complexType> 
          <xsd:sequence> 
             <xsd:element name="str" type="xsd:string" fixed="abc"/> 
             <xsd:element name="number" type="xsd:integer" fixed="123"/> 
             <xsd:element name="bool" type="xsd:boolean" fixed="true"/> 
          </xsd:sequence> 
       </xsd:complexType> 
    </xsd:element> 
    </xsd:schema> 

    <root> 
       <str/> 
       <number/> 
       <bool/> 
    </root> 

when this XML document is unmarshlled following error occurs: 

    javax.xml.bind.UnmarshalException: Zero length BigInteger 
     - with linked exception: 
    [java.lang.NumberFormatException: Zero length BigInteger] 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:728) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleError(UnmarshallingContext.java:755) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleError(UnmarshallingContext.java:751) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.handleParseConversionException(Loader.java:260) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.LeafPropertyLoader.text(LeafPropertyLoader.java:54) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.text(UnmarshallingContext.java:574) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.text(ValidatingUnmarshaller.java:115) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.processText(SAXConnector.java:198) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.endElement(SAXConnector.java:161) 
            at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:608) 
            at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183) 
            at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:355) 
            at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2790) 
            at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605) 
            at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116) 
            at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511) 
            at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:876) 
            at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:805) 
            at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:140) 
            at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1212) 
            at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214) 
            at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) 
            at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162) 
            at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171) 
            at Test7.test(Test7.java:214) 
            at Test7.main(Test7.java:109) 
    Caused by: java.lang.NumberFormatException: Zero length BigInteger 
            at java.math.BigInteger.<init>(BigInteger.java:397) 
            at java.math.BigInteger.<init>(BigInteger.java:583) 
            at com.sun.xml.internal.bind.DatatypeConverterImpl._parseInteger(DatatypeConverterImpl.java:76) 
            at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:777) 
            at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$21.parse(RuntimeBuiltinLeafInfoImpl.java:775) 
            at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:230) 
            at com.sun.xml.internal.bind.v2.runtime.unmarshaller.LeafPropertyLoader.text(LeafPropertyLoader.java:50) 
            ... 23 more 

But it seems that this documents should be processed correctly as per W3C spec [1]: 

    If fixed is specified, then the element's content must either be empty, in which case fixed behaves as default, or its value must match the supplied constraint value. 

The minimized test case is attached, actually there are two XML documents causing this error. 

In order to reproduce this error: 

1. Extract attached archive to some directory on Windows platform, say A. 
2. Change current directory to directory A. 
3. Run test7-run2.bat. 

The generated classes along with some other stuff generated from minimized testcase are attached as well. 

[1] http://www.w3.org/TR/xmlschema-1/#Element_Declaration_details

**Comment by antoniosanct** [comment] 2023-09-26 23:39
@lukasj 
Tested with master and I don't reproduce the error! Maybe could you close it?
Regards,
Antonio.

**Comment by lukasj** [comment] 2023-10-06 19:05
closing based on the latest comment

**Closed by lukasj** 2023-10-06 19:05 UTC

**Comment by galuszkak** [comment] 2024-03-14 12:34
@lukasj  @antoniosanct I've hit this error when unmarshalling XML document to classes that I genederated from XSD:
```
Exception in thread "main" java.lang.NumberFormatException: Zero length BigInteger
	at java.base/java.math.BigInteger.<init>(BigInteger.java:491)
	at java.base/java.math.BigInteger.<init>(BigInteger.java:679)
	at org.glassfish.jaxb.runtime.DatatypeConverterImpl._parseInteger(DatatypeConverterImpl.java:57)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$22.parse(RuntimeBuiltinLeafInfoImpl.java:823)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$22.parse(RuntimeBuiltinLeafInfoImpl.java:819)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:214)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:180)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:530)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:509)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:137)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:518)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:183)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:353)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:114)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:218)
	at org.glassfish.jaxb.runtime.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:189)
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:152)
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:194)
	at jakarta.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:178)
```
Versions that I'm using:
```
    implementation("jakarta.xml.bind:jakarta.xml.bind-api:4.0.2")
    implementation("com.sun.xml.bind:jaxb-impl:4.0.3")
```

**Comment by antoniosanct** [comment] 2024-03-14 19:46
@galuszkak 
I'm using master branch (>=4.0.4) and I don't have any errors. I've generated from XJC's master branch using sample XSD.

```java
//io.test.biginteger.Root.java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "str",
    "number",
    "bool"
})
@XmlRootElement(name = "root")
public class Root {

    @XmlElement(required = true)
    protected String str;
    @XmlElement(required = true)
    protected BigInteger number;
    protected boolean bool;
```

```xml
<!--sampleXML2.xml-->
<root> 
   <str/> 
   <number/> 
   <bool/> 
</root> 
```

```java
public static void main(String[] args) throws XMLStreamException, JAXBException {
	final XMLInputFactory inputFactory = XMLInputFactory.newInstance();
	final InputStream inputStream = Main.class.getResourceAsStream("/sampleXML2.xml");
	final XMLStreamReader xmlStreamReader = inputFactory.createXMLStreamReader(inputStream);
	final JAXBContext jaxbContext = JAXBContext.newInstance("io.test.biginteger",
			Thread.currentThread().getContextClassLoader());
	final Unmarshaller unmarshaller = jaxbContext.createUnmarshaller();

	xmlStreamReader.next();
	try {
		while (xmlStreamReader.hasNext()) {
			Object event = unmarshaller.unmarshal(xmlStreamReader);
			if (event instanceof Root root) {
				System.out.println(root.getStr());
				System.out.println(root.getNumber());
				System.out.println(root.isBool());
			}
		}
	} catch (UnmarshalException e) {
		e.printStackTrace();
	}
}
```

```

null
false
```

Are you considering that Root's default values are incorrect because of fixed values?

Regards,
Antonio.
